// angular-app/src/app/app.component.tsx
import React from "react";
import { Component } from "@angular/core";
import AgoraAppBuilder from "@appbuilder/web";
import useFpe from "./useFPE";

// Prevent dead code elimination on react
React.createElement("div");

@Component({
  selector: "app-root",
  template: `
    <div>
      <div style="height: 1.5rem">
        Join a meeting:
        <input id="meetingId" placeholder="meetingId" />
        <button (click)="JoinMeeting()">Join</button>
        <button (click)="Unsubscribe()">Unsubscribe</button>
      </div>
      <div style="height: calc(100vh - 1.5rem)">
        <app-builder></app-builder>
      </div>
    </div>
  `,
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title = "angular-app";
  unsubs: Array<any> = [];
  ngOnInit() {
    // FOR QA TESTING ------ FOR QA TESTING ------ FOR QA TESTING ------ FOR QA TESTING ------ FOR QA TESTING ------ FOR QA TESTING ------ FOR QA TESTING ------
    useFpe({
      topbar: false,
      chatTextInput: false,
      chatSendButton: false,
      chatBubble: false,
      participantsPanel: false,
      bottomBar: false,
      customContent: false,
      customLayout: false,
      i8n: false,
    });
    // FOR QA TESTING ------ FOR QA TESTING ------ FOR QA TESTING ------ FOR QA TESTING ------ FOR QA TESTING ------ FOR QA TESTING ------ FOR QA TESTING ------

    this.unsubs = [
      AgoraAppBuilder.on(
        "create",
        (hostMeetingId, attendeeMeetingId, pstnNumber) => {
          console.log("Angular Host App: Meeting created with", {
            hostMeetingId,
            attendeeMeetingId,
            pstnNumber,
          });
        }
      ),
      AgoraAppBuilder.on("create", () => {
        console.log("Angular Host App: Meeting created queued event");
      }),
      AgoraAppBuilder.on("ready-to-join", (meetingTitle, deviceList) => {
        console.log("Angular Host App: precall with", {
          meetingTitle,
          deviceList,
        });
      }),
      AgoraAppBuilder.on("join", (meetingTitle, deviceList, isHost) => {
        console.log("Angular Host App: joined with", {
          meetingTitle,
          deviceList,
          isHost,
        });
      }),
      AgoraAppBuilder.on("leave", () => {
        console.log("Angular Host App: left");
      }),
    ];
  }

  JoinMeeting() {
    AgoraAppBuilder.join(
      (document.getElementById("meetingId") as HTMLInputElement)!.value
    );
  }

  Unsubscribe() {
    this.unsubs.forEach((v) => {
      v();
    });
  }
  ngOnDestroy() {
    this.unsubs.forEach((v) => {
      v();
    });
  }
}

// react-app/src/App.jsx
import React, { useEffect, useState } from "react";
import Checkbox from "./CheckBox";
import AppBuilderMethods from "@appbuilder/react";
import useFPE from "./useFPE";

let unsubs;

function App() {
  const [topbar, setTopbar] = useState(false);
  const [chatTextInput, setChatTextInput] = useState(false);
  const [chatSendButton, setChatSendButton] = useState(false);
  const [chatBubble, setChatBubble] = useState(false);
  const [participantsPanel, setParticipantsPanel] = useState(false);
  const [bottomBar, setBottomBar] = useState(false);
  const [customContent, setCustomContent] = useState(false);
  const [customLayout, setCustomLayout] = useState(false);
  const [i8n, setI8n] = useState(false);

  useFPE({
    topbar,
    chatTextInput,
    chatSendButton,
    chatBubble,
    participantsPanel,
    bottomBar,
    customContent,
    customLayout,
    i8n,
  });

  useEffect(() => {
    unsubs = [
      AppBuilderMethods.on(
        "create",
        (hostMeetingId, attendeeMeetingId, pstnNumber) => {
          console.log("React Host App: Meeting created with", {
            hostMeetingId,
            attendeeMeetingId,
            pstnNumber,
          });
        }
      ),
      AppBuilderMethods.on("create", () => {
        console.log("React Host App: Meeting created queued event");
      }),
      AppBuilderMethods.on("ready-to-join", (meetingTitle, deviceList) => {
        console.log("React Host App: precall with", {
          meetingTitle,
          deviceList,
        });
      }),
      AppBuilderMethods.on("join", (meetingTitle, deviceList, isHost) => {
        console.log("React Host App: joined with", {
          meetingTitle,
          deviceList,
          isHost,
        });
      }),
      AppBuilderMethods.on("leave", () => {
        console.log("React Host App: left");
      }),
    ];
    return () => {
      unsubs.forEach((v) => {
        if (typeof v === "function") v();
      });
    };
  }, []);

  const joinMeeting = () => {
    AppBuilderMethods.join(document.getElementById("meetingId").value);
  };

  const unsubscribe = () => {
    unsubs.forEach((v) => {
      if (typeof v === "function") v();
    });
  };

  return (
    <div>
      <div
        style={{ display: "flex", overflowX: "scroll", alignItems: "center" }}
      >
        <div style={{ display: "flex", height: "3rem" }}>
          <input id="meetingId" placeholder="meetingId" />
          <button onClick={joinMeeting}>Join</button>
          <button onClick={unsubscribe}>Unsubscribe</button>
        </div>
        <div>Overrides:</div>
        <Checkbox state={{ topbar }} setter={setTopbar} />
        <Checkbox state={{ chatTextInput }} setter={setChatTextInput} />
        <Checkbox state={{ chatSendButton }} setter={setChatSendButton} />
        <Checkbox state={{ chatBubble }} setter={setChatBubble} />
        <Checkbox state={{ participantsPanel }} setter={setParticipantsPanel} />
        <Checkbox state={{ bottomBar }} setter={setBottomBar} />
        <Checkbox state={{ customContent }} setter={setCustomContent} />
        <Checkbox state={{ customLayout }} setter={setCustomLayout} />
        <Checkbox state={{ i8n }} setter={setI8n} />
      </div>
      <div
        style={{
          display: "flex",
          height: "calc( 100vh - 3rem )",
          width: "100vw",
        }}
      >
        <AppBuilderMethods.View />
      </div>
    </div>
  );
}

export default App;
